CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zippy_order_id VARCHAR(64) NOT NULL UNIQUE,
  merchant_order_id VARCHAR(64) NOT NULL UNIQUE,
  customer_name VARCHAR(120) NOT NULL,
  customer_phone VARCHAR(20) NOT NULL,
  customer_email VARCHAR(120) NOT NULL,
  pickup_address_json CLOB NOT NULL,
  delivery_address_json CLOB NOT NULL,
  pickup_pincode VARCHAR(12) NOT NULL,
  delivery_pincode VARCHAR(12) NOT NULL,
  weight_grams INTEGER NOT NULL,
  length_cm DECIMAL(10,2) NOT NULL,
  width_cm DECIMAL(10,2) NOT NULL,
  height_cm DECIMAL(10,2) NOT NULL,
  payment_type VARCHAR(16) NOT NULL,
  cod_amount DECIMAL(10,2),
  order_status VARCHAR(32) NOT NULL,
  created_at VARCHAR(40) NOT NULL,
  updated_at VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS shipping_quotes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  carrier_code VARCHAR(32) NOT NULL,
  carrier_name VARCHAR(64) NOT NULL,
  service_code VARCHAR(64) NOT NULL,
  service_name VARCHAR(128) NOT NULL,
  base_charge DECIMAL(10,2) NOT NULL,
  cod_charge DECIMAL(10,2) NOT NULL,
  additional_charges DECIMAL(10,2) NOT NULL,
  tax DECIMAL(10,2) NOT NULL,
  total_charge DECIMAL(10,2) NOT NULL,
  estimated_min_days INTEGER NOT NULL,
  estimated_max_days INTEGER NOT NULL,
  raw_carrier_response CLOB NOT NULL,
  created_at VARCHAR(40) NOT NULL,
  CONSTRAINT fk_quote_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT uq_quote UNIQUE (order_id, carrier_code, service_code)
);

CREATE TABLE IF NOT EXISTS shipments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL UNIQUE,
  carrier_code VARCHAR(32) NOT NULL,
  carrier_shipment_id VARCHAR(64),
  tracking_number VARCHAR(64),
  selected_service_code VARCHAR(64) NOT NULL,
  quoted_amount DECIMAL(10,2) NOT NULL,
  selected_quote_json CLOB NOT NULL,
  current_status VARCHAR(32) NOT NULL,
  selection_timestamp VARCHAR(40) NOT NULL,
  created_at VARCHAR(40) NOT NULL,
  updated_at VARCHAR(40) NOT NULL,
  CONSTRAINT fk_shipment_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shipment_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shipment_id BIGINT NOT NULL,
  carrier_event_id VARCHAR(120) NOT NULL,
  carrier_status VARCHAR(32) NOT NULL,
  normalized_status VARCHAR(32) NOT NULL,
  description VARCHAR(255) NOT NULL,
  location VARCHAR(120),
  event_time VARCHAR(40) NOT NULL,
  raw_event_payload CLOB NOT NULL,
  received_at VARCHAR(40) NOT NULL,
  CONSTRAINT fk_event_shipment FOREIGN KEY (shipment_id) REFERENCES shipments(id) ON DELETE CASCADE,
  CONSTRAINT uq_event UNIQUE (shipment_id, carrier_event_id)
);

CREATE TABLE IF NOT EXISTS app_meta (
  meta_key VARCHAR(64) PRIMARY KEY,
  meta_value VARCHAR(64) NOT NULL
);
