ALTER TABLE payments ADD COLUMN IF NOT EXISTS provider VARCHAR(64);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS provider_reference VARCHAR(128);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS reconciliation_reference VARCHAR(128);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS refund_reference VARCHAR(128);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS captured_at VARCHAR(40);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS collected_at VARCHAR(40);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS refunded_at VARCHAR(40);

UPDATE payments
SET provider = CASE WHEN payment_method = 'COD' THEN 'COD' ELSE 'ZIPPY_INTERNAL' END
WHERE provider IS NULL;

UPDATE payments
SET provider_reference = payment_id
WHERE provider_reference IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_payments_provider_reference
  ON payments(provider, provider_reference);

CREATE INDEX IF NOT EXISTS idx_payments_created_id
  ON payments(created_at, id);

CREATE INDEX IF NOT EXISTS idx_payments_updated_id
  ON payments(updated_at, id);

CREATE INDEX IF NOT EXISTS idx_payments_reconciliation_reference
  ON payments(reconciliation_reference);

CREATE INDEX IF NOT EXISTS idx_payments_refund_reference
  ON payments(refund_reference);

CREATE TABLE IF NOT EXISTS payment_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id VARCHAR(64) NOT NULL UNIQUE,
  payment_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  zippy_order_id VARCHAR(64) NOT NULL,
  event_type VARCHAR(40) NOT NULL,
  previous_status VARCHAR(32),
  resulting_status VARCHAR(32) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  currency VARCHAR(8) NOT NULL,
  provider VARCHAR(64) NOT NULL,
  provider_reference VARCHAR(128),
  reconciliation_reference VARCHAR(128),
  reason VARCHAR(255) NOT NULL,
  idempotency_key VARCHAR(128),
  created_at VARCHAR(40) NOT NULL,
  CONSTRAINT fk_payment_transaction_payment
    FOREIGN KEY (payment_id) REFERENCES payments(id),
  CONSTRAINT uq_payment_transaction_idempotency UNIQUE (payment_id, idempotency_key),
  CONSTRAINT chk_payment_transaction_amount CHECK (amount >= 0),
  CONSTRAINT chk_payment_transaction_event CHECK (event_type IN (
    'STATE_SNAPSHOT', 'INTENT_CREATED', 'COD_AWAITING_COLLECTION', 'CAPTURED',
    'FAILED', 'CANCELLED', 'AUTO_CANCELLED', 'AUTO_VOIDED', 'REFUND_PENDING',
    'REFUNDED', 'COD_COLLECTED'
  ))
);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_payment_time
  ON payment_transactions(payment_id, created_at, id);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_order_time
  ON payment_transactions(order_id, created_at, id);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_event_time
  ON payment_transactions(event_type, created_at, id);

INSERT INTO payment_transactions (
  transaction_id, payment_id, order_id, zippy_order_id, event_type,
  previous_status, resulting_status, amount, currency, provider,
  provider_reference, reconciliation_reference, reason, idempotency_key, created_at
)
SELECT
  CONCAT('PTX-MIGRATED-', p.id), p.id, p.order_id, p.zippy_order_id, 'STATE_SNAPSHOT',
  NULL, p.status, p.amount, p.currency, p.provider,
  p.provider_reference, p.reconciliation_reference,
  'State snapshot created by payment ledger migration', NULL, p.updated_at
FROM payments p
WHERE NOT EXISTS (
  SELECT 1 FROM payment_transactions t WHERE t.payment_id = p.id
);
